travis:
  secure:
    BINSTAR_TOKEN: oc72Epw0DkRVSucZKIKdhbKL2BNWobB0/HgNl9AHcqmT5PRBhx09xrWiH10ws0Qb/xPkPtxTSBsu5K74CtH90M4ROO2aw7LTmqLtFpj6HsFRocnfPIGlUuLcUuXoTgZvZFIC8c52IGi344FGxFlD7ZGfp+99VERIfhfbjBKue5N3KZSUFwXK2JRBIg1C5Da806ZaCiwO5WUQLM8ogkyXMUBVVRjyiOlFJ2H9mIbtMPR5fjnypEEwELxvRopkudtLAhR4xgA0uoJH8GlpJ4UGkwHj/f/l4EIudlQOQu7CeoJmNgR3GFPZh7RWO/lhMMSNwtmGnu6TuPXxz5Tp+l3rMDDYLF3VGCzdiBZ8HoLG2Roc6YOBq0Qxx3MISfm2LPImU0QuzBo8fic9kcGUkbaf2wUyBX/W3Sfb1AWSJHwMnqLQDHsae2HJiOlpT6Q6F8EXcOlPzPaZyoAkK6oaTbyUSOikLPnTUfp5Em1qvw8rJsb9Gyr6Wjp1zKcZSSkgM3SsVWzTdvAGb8WXCIq5XXYY7fm+DPH0kjdANz+PaJr3TpCRid8NsWuDED71D/mrgel9YvFz9AqsJ9juAtID9dl8O883VfRPTOMA92BdUq4g56q5UzHiQavusmgUXz+9HQSPgya/ouvTo/u/cS02hfyEYTApRAQagDgO/ktIR75UV6U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
