appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: Z+LPrJ9Jaca2EEunKJfEqoG/Otm+8s5P5GK0Bjov10bmXwoA/h300+QxZKYYaUQk4GI1xtKZDMCxKbOdbmmHEySWoxCAhvkwG7g5Eld4NmTyuowdhf3G5vBhOPCsNmbziqz4oj2+HJ+/UQv4sRtmwO6yTV1TpqM+zdkB+X3LcE4BJPsCxF9SrtvNmGBm/uCjg1+qahOZF76NyAznbMq+NiTeh1Li2XhPI8qPGiOspzLsxzwviHaqDTFAQln7mn5Puw/E8YV0ZLdn+gaGEVKWgLHNutbNP7GV9mV43JiSIS/WfkZ5YOCXt0fbwaqxg7KjtewY5GgRQMHbJozCF/zvadGknxSiWXKqVuN9SHSvvqzIVP7OAQlHARKDdQDfWtpSmII91sRjpdVdsSAZhAAMxMUQx/iT5nRzrQmyZ8QGE6lOlJQ+ou0ZAabo4LhgVtxbZC+7eODLT6zgiu3NdYY5Q7zigdXN2AS2ZqO6o24OY5MAvtkeaGkeo/BEPPMrhrdKzmTyopWYaep7/xCFH2xN8ASJF1pLnsRsxrf3wjiXM0Y4MQR5Qvt1edjUcC0qBZM039UhvYbEjLXzXOBa/4dTcN0xR0+SYbbHl5b5cZLdR10WRs3Y4zo34GFnrvdtoPYAqCpxrEC0gdOG2APMTZDQIdmcm2QKCKI3Al5yWS33g+w=
conda_forge_output_validation: true
