travis:
  secure:
    BINSTAR_TOKEN: rbkeRaCoPFNFvdyFGxvBqnf0s/9gRFGhKDhMsQEeZzDpwhwZNzWyP6TsB8avHdvC3Tq3e/r2n92a7XCx6snFFpBop0gwNlDFkek1qvLDnnb2TsQqGMTtshFiTSoQ7at+VLPxzdV7nW8Npxfd93cpuUCSinv4me91zQ1NkFW8tfgIGzo74E5GnkHDmWi59iTa7FVR9VlXvjAQi2sh2v7oEGM5h2hBlRRvzAsIEk2gBIJcRGXa9NbXLlgzElt8CwsIn+/O1kZnBeh5Gh45ToI2Oz7FOeyEEECA7CNSczQUdCaGu1p7zPT2ycWMqBprj02WXpxlCZUffWSNdHA8J4g/qscqhhJj6egHyozItmRd3Tv9EcdtAFSpSqln0b3EyLpJZM82se948DQDs7dUN0mChJnGOL6yBqZf1GR/7E89+J2wAdEwXUmrepSzlpCDEtLsKHpT3yinvr3/CzBcqgMEw3T0X4SmND2BFv1dYTTk0SfVTNoWk3s5v+WCYvcbpPRw7ONMt5gQCusltIzsJrh2ZpB1P0SlS92NG0/aK0tYWQ0ds06+OeUW4vsY2CToog6O9cN5b+m2EVbToLWUx7Xae6hIumTz+SsUklrLtVqktdz22/DCc2Zmdx+TB//dc6I1TWcMmwEmcoQp+GTo/ONoIAX3T0CC2Ka27mqQ8Y5AkA4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
